version: '3.8'

services:
  streamlit-app:
    # IMPORTANTE: Aquí usamos la imagen de Docker Hub, no construimos localmente
    # Cambia 'tu_usuario' y 'mi-streamlit-app' por los tuyos reales
    image: ghcr.io/jornkbz/tfm-eip:latest
    
    container_name: airplane-streamlit-app
    
    ports:
      - "8501:8501"
    networks:
      - neura_django
    # En producción NO mapeamos las carpetas de código (Streamlit_app, ML-Models)
    # porque el código ya vive dentro de la imagen.
    # Solo mapeamos volúmenes si necesitas guardar datos (ej: una base de datos)
    # volumes:
    #   - ./datos_persistentes:/app/data

    restart: always

networks:
  neura_django:
    external: true
    